#OpticsValley IRC server configuration
#Sun Sep 13 22:10:39 SGT 2026
connection.handshake-timeout-millis=10000
connection.outbound-queue-capacity=100
message.max-length=80
rate-limit.burst=10
rate-limit.max-violations=20
rate-limit.messages-per-second=5.0
server.bind-address=0.0.0.0
server.gui=true
server.max-clients=100
server.port=16688
storage.ban-file=bans.json
username.max-length=32
