package com.dioxidelite.client.modules.impl.Render;

import com.dioxidelite.Config; import com.dioxidelite.client.modules.impl.Tool.BlockCountDisplayRenderer; import net.minecraft.client.Minecraft; import net.minecraft.client.gui.GuiGraphics; import org.lwjgl.glfw.GLFW;

/** Native HUD editor: drag outlines and scroll-to-scale, with cheap grid/snap guides. */
public final class HudEditOverlay {
    private static final HudEditOverlay INSTANCE=new HudEditOverlay(); private enum Target{NONE,TARGET,KEYS,BLOCK,ARMOR,NOTIFY,POTION}; private Target drag=Target.NONE; private boolean down; private float ox,oy; private boolean active,closing; private long animAt; private float alpha; private float grid;
    public static HudEditOverlay getInstance(){return INSTANCE;} public boolean isActive(){return active;}
    public void startOpen(){active=true;closing=false;animAt=System.currentTimeMillis();NotificationOverlay.getInstance().startEditPreview();}
    public void startClose(){if(!active)return;closing=true;animAt=System.currentTimeMillis();NotificationOverlay.getInstance().stopEditPreview();}
    public void render(GuiGraphics g){if(!active)return;Minecraft mc=Minecraft.getInstance();int w=mc.getWindow().getGuiScaledWidth(),h=mc.getWindow().getGuiScaledHeight();long now=System.currentTimeMillis();float t=Math.min(1,(now-animAt)/200f);alpha=closing?1-t:t;if(closing&&alpha<=0){active=false;drag=Target.NONE;return;}grid+=(drag!=Target.NONE?1-grid:0-grid)*.18f;int ga=Math.round(255*.25f*alpha*grid);for(int i=1;i<3;i++){int xx=w*i/3,yy=h*i/3;g.fill(xx,0,xx+1,h,(ga<<24)|0xFFFFFF);g.fill(0,yy,w,yy+1,(ga<<24)|0xFFFFFF);}draw(g,targetRect(w,h),"Target HUD",Target.TARGET);draw(g,keysRect(w,h),"Keystrokes",Target.KEYS);draw(g,blockRect(w,h),"Block Count",Target.BLOCK);draw(g,armorRect(w,h),"Armor HUD",Target.ARMOR);draw(g,notifyRect(w,h),"Notification",Target.NOTIFY);draw(g,potionRect(w,h),"Potion Status",Target.POTION);String hint=Config.isChinese?"悬浮组件拖动位置 · 滚轮调整大小":"Drag widgets to reposition · scroll to resize";g.drawString(mc.font,hint,(w-mc.font.width(hint))/2,h-28,(Math.round(255*.7f*alpha)<<24)|0xEAF2F4,false);long handle=mc.getWindow().handle();double[] rx={0},ry={0};GLFW.glfwGetCursorPos(handle,rx,ry);float mx=(float)(rx[0]/mc.getWindow().getGuiScale()),my=(float)(ry[0]/mc.getWindow().getGuiScale());boolean md=GLFW.glfwGetMouseButton(handle,GLFW.GLFW_MOUSE_BUTTON_LEFT)==GLFW.GLFW_PRESS;if(md&&!down){Rect r=pick(w,h,mx,my);if(r!=null){drag=r.target;ox=mx-r.x;oy=my-r.y;}}if(!md){drag=Target.NONE;}down=md;if(drag!=Target.NONE&&md){Rect r=pick(w,h,mx,my);if(r!=null){float nx=Math.max(0,Math.min(w-r.w,mx-ox)),ny=Math.max(0,Math.min(h-r.h,my-oy));setPosition(r.target,nx,ny,w,h);}}}
    private void draw(GuiGraphics g,Rect r,String label,Target t){if(r==null)return;int c=(Math.round(255*(is(t)?1:.45f)*alpha)<<24)|0x78CFFF;g.renderOutline(Math.round(r.x)-4,Math.round(r.y)-4,Math.round(r.w)+8,Math.round(r.h)+8,c);g.drawString(Minecraft.getInstance().font,label,Math.round(r.x)-2,Math.max(2,Math.round(r.y)-16),(Math.round(255*.65f*alpha)<<24)|0xFFFFFF,false);}
    private boolean is(Target t){return drag==t;}
    private Rect targetRect(int w,int h){float s=Math.max(.5f,Config.targetHudScale);return rect(w*.5f+Config.targetHudX,h*.5f+Config.targetHudY,190*s,58*s,Target.TARGET,w,h);}private Rect keysRect(int w,int h){KeystrokesRenderer r=KeystrokesRenderer.getInstance();return rect(r.getRenderX(w),r.getRenderY(h),r.getScaledWidth(),r.getScaledHeight(),Target.KEYS,w,h);}private Rect blockRect(int w,int h){BlockCountDisplayRenderer r=BlockCountDisplayRenderer.getInstance();return rect(r.getRenderX(w),r.getRenderY(h),r.getEditWidth(),r.getEditHeight(),Target.BLOCK,w,h);}private Rect armorRect(int w,int h){ArmorHudRenderer r=ArmorHudRenderer.getInstance();return rect(r.getRenderX(w),r.getRenderY(h),r.getEditWidth(),r.getEditHeight(),Target.ARMOR,w,h);}private Rect notifyRect(int w,int h){NotificationOverlay r=NotificationOverlay.getInstance();int rw=r.getEditWidth(),rh=r.getEditHeight();return rect(r.getRenderX(w,rw),r.getRenderY(h),rw,rh,Target.NOTIFY,w,h);}private Rect potionRect(int w,int h){PotionStatusRenderer r=PotionStatusRenderer.getInstance();return rect(r.getRenderX(w),r.getRenderY(h),r.getEditWidth(),r.getEditHeight(),Target.POTION,w,h);}
    private Rect pick(int w,int h,float x,float y){Rect[] rs={targetRect(w,h),keysRect(w,h),blockRect(w,h),armorRect(w,h),notifyRect(w,h),potionRect(w,h)};for(Rect r:rs)if(r!=null&&r.contains(x,y))return r;return null;}
    private Rect rect(float x,float y,float rw,float rh,Target t,int w,int h){return new Rect(Math.max(0,Math.min(w-rw,x)),Math.max(0,Math.min(h-rh,y)),rw,rh,t);}
    private void setPosition(Target t,float x,float y,int w,int h){switch(t){case TARGET-> {Config.targetHudX=x-w*.5f;Config.targetHudY=y-h*.5f;}case KEYS->{Config.keystrokesX=x-w*.5f;Config.keystrokesY=y-h*.5f;}case BLOCK->{BlockCountDisplayRenderer r=BlockCountDisplayRenderer.getInstance();Config.blockCountDisplayX=x-(w-r.getEditWidth())*.5f;Config.blockCountDisplayY=y-r.getDefaultY(h);}case ARMOR->{ArmorHudRenderer r=ArmorHudRenderer.getInstance();Config.armorHudX=x-(w-r.getEditWidth())*.5f;Config.armorHudY=y-h*.5f;}case NOTIFY->{Config.notificationX=x+getNotifyW()-w*.5f;Config.notificationY=y-h*.5f;}case POTION->{PotionStatusRenderer r=PotionStatusRenderer.getInstance();Config.potionStatusX=x-r.getDefaultX();Config.potionStatusY=y-(h-r.getEditHeight())*.5f;}default->{}}Config.save();}
    private int getNotifyW(){return NotificationOverlay.getInstance().getEditWidth();}
    public boolean mouseScrolled(double mx,double my,double amount){if(!active)return false;Minecraft mc=Minecraft.getInstance();int w=mc.getWindow().getGuiScaledWidth(),h=mc.getWindow().getGuiScaledHeight();Rect r=pick(w,h,(float)mx,(float)my);if(r==null)return false;float d=amount>0?.05f:-.05f;switch(r.target){case TARGET->{Config.targetHudScale=clamp(Config.targetHudScale+d);}case KEYS->{Config.keystrokesScale=clamp(Config.keystrokesScale+d);}case BLOCK->{Config.blockCountDisplayScale=clamp(Config.blockCountDisplayScale+d);}case ARMOR->{Config.armorHudScale=clamp(Config.armorHudScale+d);}case NOTIFY->{Config.notificationScale=clamp(Config.notificationScale+d);}case POTION->{Config.potionStatusScale=clamp(Config.potionStatusScale+d);}default->{return false;}}Config.save();return true;}
    public void renderFrameEnd(){}
    private float clamp(float v){return Math.max(.5f,Math.min(2f,v));}
    private record Rect(float x,float y,float w,float h,Target target){boolean contains(float mx,float my){return mx>=x-4&&mx<=x+w+4&&my>=y-4&&my<=y+h+4;}}
}
