package com.dioxidelite.client.modules.impl.Tool;

import com.dioxidelite.Config; import com.dioxidelite.client.modules.impl.Render.HudEditOverlay; import com.dioxidelite.client.render.nativeui.NativeGlassVisualSystem; import net.minecraft.client.Minecraft; import net.minecraft.client.gui.GuiGraphics; import net.minecraft.world.item.ItemStack;

/** Native block count/status display. */
public final class BlockCountDisplayRenderer {
    private static final BlockCountDisplayRenderer INSTANCE=new BlockCountDisplayRenderer(); private final RateCounter clicks=new RateCounter(),placements=new RateCounter(); private boolean visible; private long until; private ItemStack stack=ItemStack.EMPTY; private float anim; private int lastSlot=-1,lastCount=-1;
    public static BlockCountDisplayRenderer getInstance(){return INSTANCE;}
    public boolean needsCanvas(){return false;} public float getEditWidth(){return 190*Math.max(.5f,Config.blockCountDisplayScale);}public float getEditHeight(){return 58*Math.max(.5f,Config.blockCountDisplayScale);}public float getDefaultY(int h){return h*.5f-getEditHeight()/2;}public float getRenderX(int w){return w*.5f+Config.blockCountDisplayX-getEditWidth()/2;}public float getRenderY(int h){return h*.5f+Config.blockCountDisplayY-getEditHeight()/2;}
    public void tick(Minecraft mc){if(!Config.blockCountDisplay||mc.player==null)return;ItemStack held=mc.player.getMainHandItem();int slot=mc.player.getInventory().getSelectedSlot(),count=held.isEmpty()?0:held.getCount();if(slot!=lastSlot||count!=lastCount){if(!held.isEmpty()){stack=held.copy();visible=true;until=System.currentTimeMillis()+900;anim=0;}lastSlot=slot;lastCount=count;}}
    public void triggerUse(Minecraft mc){if(!Config.blockCountDisplay)return;clicks.record();visible=true;until=System.currentTimeMillis()+900;stack=mc.player==null?ItemStack.EMPTY:mc.player.getMainHandItem().copy();}
    public void recordPlacement(Minecraft mc){if(!Config.blockCountDisplay)return;placements.record();visible=true;until=System.currentTimeMillis()+900;stack=mc.player==null?ItemStack.EMPTY:mc.player.getMainHandItem().copy();}
    public void render(GuiGraphics g, Object ignored){Minecraft mc=Minecraft.getInstance();if(!Config.blockCountDisplay||mc.player==null)return;long now=System.currentTimeMillis();float dt=.016f;if(visible)anim=Math.min(1,anim+dt*6);else anim=Math.max(0,anim-dt*6);if(now>until)visible=false;if(!visible&&anim<=0)return;float s=Math.max(.5f,Config.blockCountDisplayScale),w=190,h=58;int x=Math.round(getRenderX(mc.getWindow().getGuiScaledWidth())),y=Math.round(getRenderY(mc.getWindow().getGuiScaledHeight()));NativeGlassVisualSystem.renderHudDock(g,x,y,Math.round(w*s),Math.round(h*s),.78f*anim);g.pose().pushMatrix();g.pose().translate(x,y);g.pose().scale(s,s);if(!stack.isEmpty()){g.renderFakeItem(stack,12,12);g.renderItemDecorations(mc.font,stack,12,12);}String name=stack.isEmpty()?"Block":stack.getHoverName().getString();if(name.length()>18)name=name.substring(0,18)+"…";g.drawString(mc.font,name,48,12,0xF0F5F7,false);g.drawString(mc.font,"COUNT "+(stack.isEmpty()?0:stack.getCount()),48,27,0xB9C6CC,false);g.drawString(mc.font,"RMB "+clicks.getCps()+"   PLACE "+placements.getCps(),48,41,0x788992,false);g.pose().popMatrix();}
    public void renderFrameEnd(){}
    private static final class RateCounter{private final java.util.ArrayDeque<Long> q=new java.util.ArrayDeque<>();void record(){long n=System.currentTimeMillis();q.add(n);while(!q.isEmpty()&&n-q.peek()>1000)q.poll();}int getCps(){long n=System.currentTimeMillis();while(!q.isEmpty()&&n-q.peek()>1000)q.poll();return q.size();}}
}
